### ISSUE TITLE
Change how files are served to the client

### ISSUE THREAD

**Issue by blacksmithop** [blacksmithop/imgen#2]
Problem:
Right now a .extension (jpg,png etc) file is created for every request and that is returned as the response (file overwritten when new one comes).
Possible Solutions/ Changes Expected:
Implement a better alternative which could be using uuid to name the output, or returned a SpooledTemporaryFile or returning the bytes data as itself. These are just possible solutions, PR's are open to other solutions.

**Comment by ssiyad** [comment]
It looks like bytes data can not be used in aiohttp responses `(https://docs.aiohttp.org/en/stable/web_reference.html#response-classes)`. So I assume the best possible way to tackle this problem would be to make use of uuid.

**Comment by ssiyad** [comment]
Forgot this: https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile

**Comment by ssiyad** [comment]
aiohttp still haven't added support for tempfiles as [this issue](https://github.com/aio-libs/aiohttp/issues/4432) shows

**Comment by blacksmithop** [comment]
@ssiyad Thanks for looking into this. It seems like we could go ahead with the uuid approach. Something along the lines of keeping a directory of image results that are named using uuid and periodically emptied.

**Comment by blacksmithop** [comment]
Tested it out on the Heroku instance, files are being served correctly. Thanks for the contribution 👍
