### ISSUE TITLE
Can i actually use this fork or do i jave to self host it?

### ISSUE THREAD

**Issue by nettlees** [blacksmithop/imgen#6]
What the title says, but just to say when using this version it keeps on saying I sent a bad request any help

**Comment by blacksmithop** [comment]
Can you tell which branch you were using? I remember setting dev as the default after fixing a couple of bugs. Can you provide screenshots of what you see while running it?
 You can host this on Heroku by clicking the button under readme, as well run it on your local/ remote machine.

**Comment by nettlees** [comment]
I seem to have fixed the error oddly I did not change a thing. Just a quick question. Can I use this api like any normal api for example how you would use https://nekos.life ?

**Comment by blacksmithop** [comment]
The API is documented under the docs section, you can follow those instructions on how you can pass data to an endpoint, the response is a 200 (if you did everything contently) and the response data can be saved as image/used directly.
